service: my-app
image: my-user/my-app
servers:
  web:
    - 192.168.0.1
proxy:
  ssl: true
  host: app.example.com
registry:
  username: my-user
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
